apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "backend.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "backend.fullname" . }}
    spec:
      containers:
        - image: counter-backend:1.2.0
          imagePullPolicy: IfNotPresent
          name: {{ include "backend.fullname" . }}
          env:
            - name: CACHE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-database-secret
                  key: user
            - name: CACHE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-database-secret
                  key: password
            - name: CACHE_HOST
              value: {{ .Release.Name }}-database
            - name: CACHE_PORT
              value: "{{ .Values.database.port }}"
          ports:
            - containerPort: {{ .Values.port }}
